### ISSUE TITLE
react-native 0.51.0 release issues with react-native-linear-gradient

### ISSUE THREAD

**Issue by jdonisvitch** [heineiuo/react-native-animated-linear-gradient#14]
First off, thanks for the sweet library. 🎉 

While working to update to the latest release, I ran into issues with the underlying library and the community around it figured out that `start` and `end` are now reserved. See notes here in this PR:

https://github.com/react-native-community/react-native-linear-gradient/pull/243

When that fix does happen, or whatever fix is made for that issue, your code will need to be changed from `start` and `end` to `startPoint` and `endPoint`, or whatever the vars end up being. I tried it locally, and it looks to work, could work up a PR if you're interested.

Cheers,

**Comment by joncursi** [comment]
I am using `bilalsyed001`'s fork of `react-native-linear-gradient` to get it to work with RN 0.51.0 and I indeed had to rename the `start` and `end` props in this lib to `startPoint` and `endPoint` (these were the new names chosen by the fork I'm using).

**Comment by jdonisvitch** [comment]
Looks like the react-native-linear-gradient team has figured out a way to achieve this fix without affecting the external api. 

https://github.com/react-native-community/react-native-linear-gradient/pull/235

It may make sense to leave this card open until that specific PR gets merged in. It requires no code changes (if that PR is the fix), so this could be closed.

Best,

**Comment by jdonisvitch** [comment]
Fixed in the latest merge react-native-community/react-native-linear-gradient#235
