### ISSUE TITLE
Huge CPU usage, drains energy on devices.

### ISSUE THREAD

**Issue by qudde** [heineiuo/react-native-animated-linear-gradient#19]
We implemented this component for a production application instead of just a static background colored view. We saw a huge increase in CPU usage and energy consumption of about 70-80% in xcode while using 1 or 2 of this components. When we removed it, the CPU usage dropped to about 0-10%, så this is absolutely attributable to this particular component.

Is this something you have planned to fix or address? For now i don't think anyone should use this component in production as it will drain the consumer devices battery really fast and consume way to much CPU. The workaround is of course to just use an animated video/image as a background, but we wanted this component because we have a theming system and want our users to be able to select from different app themes, so it was convenient.

**Comment by laychar** [comment]
Did you fix this problem?
I consider whether I should use this plugin or not because of battery draining.

**Comment by nickmccomb** [comment]
This is related to useNativeDriver.. This library is unusable at the moment, it drains users' batteries and i can't even dev on my machine with this in my app, my laptop grinds to a halt.   Needs to use useNativeDriver: true on the Animation.timing, without it the library is too resource heavy and shouldn't be used in any app

**Comment by jamesdunay** [comment]
Still seeing high CPU usage from this component, but also getting the warning that 'useNativeDriver' wasn't specified. 

Running 
react-native 0.62.2
react-native-animated-linear-gradient ^1.2.2
