### ISSUE TITLE
Please set useNativeDriver to true.

### ISSUE THREAD

**Issue by tswapy** [heineiuo/react-native-animated-linear-gradient#47]
A warning keep appearing to set useNativeDrive to true while using this component.

**Comment by heineiuo** [comment]
@tswapy Could you please copy the warnings or take a screenshot? And maybe you can create PR for this, I'm glad to review and merge.

**Comment by RFDO93** [comment]
a mi me pasa lo mismo, adjunto capture 

(Animated: `useNativeDriver` was not specified. This is a required option and must be explicitly set to `true` or `false`)

![Captura de Pantalla 2020-04-20 a la(s) 11 14 41](https://user-images.githubusercontent.com/10853457/79768075-3faca200-82f8-11ea-8df3-dc4d91870c21.png)

**Comment by RFDO93** [comment]
I get the same warning, (Animated: `useNativeDriver` was not specified. This is a required option and must be explicitly set to` true` or `false`), attached log screenshot

![Captura de Pantalla 2020-04-20 a la(s) 11 14 41](https://user-images.githubusercontent.com/10853457/79768404-bd70ad80-82f8-11ea-80f4-29a1f03a3c1d.png)

**Comment by nickmccomb** [comment]
Not using native driver is spiking my CPU up to 140%.  Can't use this library without useNativeDriver, it kills users' batteries.

**Comment by nickmccomb** [comment]
Also kills development, laptop slows down drastically to the point can't do any work properly.

**Comment by heineiuo** [comment]
@tswapy  @RFDO93  @nickmccomb  v1.2.2 published.

**Comment by fbotalla** [comment]
Hello! are you guys working on this? I am using v1.2.2 and this warning is still happening. It really makes the overall performance of the app much slower. Any news?
